//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr19_7._1_Likhachev_Miroshnichenko.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ijhlvkfgesjkfgreuygiel;wfgredsyghiuyreg\r\n okn esbz и8шгнпку\r\n НЕПЧ ПРЫКВГНФЯ ХЛ О" +
            " АШЩУЯРЫ\r\nЪХ БшгщкДЕИПМНЕКУЯВЧ НТЧЬ ВЫАПНР\r\nЪА ВЧШ5ЛЩОЗАВКНЩШЛЖТКЕГЫДТЛОА\r\nХДПЧТ" +
            "98ГН")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
